-- MIMOS Academy PMS V2 — deterministic migration apply order
-- ---------------------------------------------------------------------------
-- This is the authoritative, ordered list of EVERY migration in
-- supabase/migrations/, in exact filename order, ready to paste into the
-- Supabase SQL Editor (one file at a time, top to bottom, in this order).
--
-- WHY NOT `supabase db push`?
--   The repo uses 3-digit prefixes (001_... , 048_...). The Supabase CLI
--   records versions as the leading number and expects timestamp-prefixed
--   names; a mismatch (e.g. a recorded `20260827033124`) means the CLI will
--   not reconcile these filenames. Applying file-by-file in this order is
--   deterministic and reproducible.
--
-- HOW TO USE (two options)
--   A) Supabase dashboard -> SQL Editor: paste the CONTENTS of each file
--      below in the order listed, run one file at a time (stop on error).
--   B) Supabase CLI with psql (idempotent, transactional per file):
--      for f in $(cat supabase/migrations/version-order.txt); do \
--        psql "$DB_URL" -v ON_ERROR_STOP=1 -f "supabase/migrations/$f"; done
--   B is recommended because ON_ERROR_STOP=1 aborts the run on first error.
--
-- ───────────────────────────────────────────────────────────────────────────
-- ORDER (45 files; no file 024 / 046 / 047 — intentional gaps)
-- ───────────────────────────────────────────────────────────────────────────
-- 001_extensions.sql
-- 002_lookup_tables.sql
-- 003_master_tables.sql
-- 004_core_financial_tables.sql
-- 005_operations_tables.sql
-- 006_staging_import.sql
-- 007_audit_conflict.sql
-- 008_triggers.sql
-- 009_functions.sql
-- 010_views.sql
-- 011_rls.sql
-- 012_storage.sql
-- 013_audit_actor_mapping.sql
-- 014_staging_promotion.sql
-- 015_migration_function_security.sql
-- 016_security_integrity_hardening.sql
-- 017_authorization_boundary_hardening.sql
-- 018_application_transaction_hardening.sql
-- 019_application_transaction_hardening.sql
-- 020_private_authorization_execution.sql
-- 021_financial_domain_invariants.sql
-- 022_financial_relationship_integrity.sql
-- 023_authoritative_invoice_accounting.sql
-- 025_financial_amount_relationship_guards.sql
-- 026_raw_data_intake_pipeline.sql
-- 027_data_change_ledger.sql
-- 028_data_completeness_engine.sql
-- 029_lifecycle_completeness_rules.sql
-- 030_import_change_set.sql
-- 031_safe_change_set_promotion.sql
-- 032_import_pipeline_integrity.sql
-- 033_import_audit_immutability.sql
-- 034_import_approval_integrity.sql
-- 035_import_mapping_rules.sql
-- 036_change_set_apply_engine.sql
-- 037_import_hash_and_concurrency.sql
-- 038_import_concurrency_guard.sql
-- 039_import_canonical_hash.sql
-- 040_import_mapping_corrections.sql
-- 041_import_promotion_integrity.sql
-- 042_import_hash_alignment.sql
-- 043_quotation_state_transition_role_fix.sql
-- 044_private_authorization_helpers.sql
-- 045_participant_client_fk.sql
-- 048_masb_team_full_operational_access.sql
--
-- After applying all 45, run the read-only regression/security checks in
-- supabase/tests/*.sql (11 files). See .handoff/DEPLOY_RUNBOOK.md.
-- ---------------------------------------------------------------------------
