-- 033_import_mapping_rules.sql
create schema if not exists intake;
create table if not exists intake.field_mapping (id bigint generated always as identity primary key,target_table text not null,source_field text not null,target_field text not null,required boolean not null default false,transform text not null default 'TRIM',unique(target_table,source_field));
insert into intake.field_mapping(target_table,source_field,target_field,required,transform) values
('client','client_id','id',false,'INTEGER'),('client','company_name','company_name',true,'TRIM'),('client','client_name','company_name',true,'TRIM'),('client','name','company_name',true,'TRIM'),('client','registration_number','registration_number',false,'TRIM'),
('programme','programme_id','id',false,'INTEGER'),('programme','programme_code','programme_code',false,'TRIM'),('programme','programme_name','title',true,'TRIM'),('programme','title','title',true,'TRIM'),('programme','client_id','client_id',true,'INTEGER'),('programme','start_date','start_date',false,'DATE'),('programme','end_date','end_date',false,'DATE'),
('quotation','quotation_id','id',false,'INTEGER'),('quotation','quotation_no','quotation_no',true,'TRIM'),('quotation','quotation_number','quotation_no',true,'TRIM'),('quotation','programme_id','programme_id',true,'INTEGER'),('quotation','client_id','client_id',true,'INTEGER'),('quotation','final_price','final_price',false,'DECIMAL'),
('purchase_order','po_id','id',false,'INTEGER'),('purchase_order','po_no','po_no',true,'TRIM'),('purchase_order','po_number','po_no',true,'TRIM'),('purchase_order','programme_id','programme_id',true,'INTEGER'),('purchase_order','client_id','client_id',true,'INTEGER'),('purchase_order','po_value_excl_tax','po_value_excl_tax',false,'DECIMAL'),
('invoice','invoice_id','id',false,'INTEGER'),('invoice','invoice_no','invoice_no',true,'TRIM'),('invoice','invoice_number','invoice_no',true,'TRIM'),('invoice','programme_id','programme_id',true,'INTEGER'),('invoice','client_id','client_id',true,'INTEGER'),('invoice','amount_excl_tax','amount_excl_tax',false,'DECIMAL'),('invoice','total_incl_tax','total_incl_tax',false,'DECIMAL'),
('payment','payment_id','id',false,'INTEGER'),('payment','payment_reference','payment_reference',true,'TRIM'),('payment','invoice_id','invoice_id',true,'INTEGER'),('payment','programme_id','programme_id',false,'INTEGER'),('payment','client_id','client_id',false,'INTEGER'),('payment','amount','amount',true,'DECIMAL'),('payment','payment_date','payment_date',false,'DATE')
on conflict(target_table,source_field) do update set target_field=excluded.target_field,required=excluded.required,transform=excluded.transform;
alter table intake.field_mapping enable row level security;
revoke all on intake.field_mapping from anon,authenticated;
comment on table intake.field_mapping is 'Explicit allow-list preventing arbitrary raw-file columns from becoming database columns.';
