import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const ALLOWED_TABLES = new Set(['client','programme','quotation','purchase_order','invoice','payment','staff']);
const ADMIN_ROLES = new Set(['SUPER_ADMIN','ADMIN','DATA_ADMIN']);
const headers = (req: Request) => { const allowed = new Set([Deno.env.get('APP_ORIGIN') ?? '', Deno.env.get('VITE_APP_ORIGIN') ?? ''].filter(Boolean)); const o=req.headers.get('Origin')??''; const h:Record<string,string>={'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'}; if(allowed.has(o)) h['Access-Control-Allow-Origin']=o; return h; };
const json=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...headers(req),'Content-Type':'application/json'}});
function norm(v:unknown){return v===null||v===undefined?'':String(v).trim().toLowerCase().replace(/\s+/g,' ')}
function hash(o:Record<string,unknown>){let s=Object.keys(o).sort().map(k=>`${k}:${norm(o[k])}`).join('|'),h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
function identity(table:string,r:Record<string,unknown>){const fields:Record<string,string[]>= {client:['client_id','email'],programme:['programme_id'],quotation:['quotation_id','quotation_number'],purchase_order:['po_number'],invoice:['invoice_id','invoice_number'],payment:['payment_id','payment_reference'],staff:['staff_id','email']}; for(const f of fields[table]??[]) if(norm(r[f])) return {field:f,value:norm(r[f])}; return null;}
Deno.serve(async req=>{ if(req.method==='OPTIONS') return new Response('ok',{headers:headers(req)}); if(req.method!=='POST') return json(req,{error:'Method not allowed'},405); try { const a=req.headers.get('Authorization'); if(!a?.startsWith('Bearer ')) return json(req,{error:'Authentication required'},401); const url=Deno.env.get('SUPABASE_URL')!, anon=Deno.env.get('SUPABASE_ANON_KEY')!; const client=createClient(url,anon,{global:{headers:{Authorization:a}}}); const {data:{user},error}=await client.auth.getUser(); if(error||!user)return json(req,{error:'Authentication required'},401); const {data:me}=await client.from('staff').select('staff_role:staff_role(code)').eq('auth_user_id',user.id).eq('is_active',true).maybeSingle(); const role=me?.staff_role?.code; if(!ADMIN_ROLES.has(role))return json(req,{error:'Data administration access required'},403); const body=await req.json().catch(()=>null); const rows=Array.isArray(body?.rows)?body.rows:[]; if(!rows.length||rows.length>5000)return json(req,{error:'rows must contain 1 to 5000 records'},400); const results=[]; for(let i=0;i<rows.length;i++){const r=rows[i] as Record<string,unknown>, table=typeof body?.target_table==='string'?body.target_table:null; if(!table||!ALLOWED_TABLES.has(table)){results.push({row_number:i+1,operation:'REVIEW',reason:'Invalid or missing target table'});continue;} const id=identity(table,r); if(!id){results.push({row_number:i+1,operation:'REVIEW',target_table:table,confidence:0,reason:'No deterministic identity'});continue;} const {data,error:e}=await client.from(table).select('*').eq(id.field,id.value).limit(2); if(e){results.push({row_number:i+1,operation:'REVIEW',target_table:table,confidence:0,reason:'Canonical lookup failed'});continue;} if(!data?.length){results.push({row_number:i+1,operation:'NEW',target_table:table,target_id:null,confidence:1,reason:`No existing ${id.field} found`,proposed_payload:r,payload_hash:hash(r)});continue;} if(data.length>1){results.push({row_number:i+1,operation:'CONFLICT',target_table:table,target_id:null,confidence:0,reason:`Multiple canonical records matched ${id.field}`,proposed_payload:r});continue;} const existing=data[0] as Record<string,unknown>, changed:string[]=[]; for(const [k,v] of Object.entries(r)) if(norm(existing[k])!==norm(v)) changed.push(k); results.push({row_number:i+1,operation:changed.length?'UPDATE':'UNCHANGED',target_table:table,target_id:existing.id??null,confidence:1,reason:changed.length?'Deterministic identity match with field changes':'Deterministic identity match; no field changes',changed_fields:changed,expected_existing_hash:hash(existing),proposed_payload:r,payload_hash:hash(r)}); } return json(req,{results,counts:Object.fromEntries(['NEW','UPDATE','UNCHANGED','DUPLICATE','CONFLICT','REVIEW','REJECT'].map(x=>[x,results.filter((r:any)=>r.operation===x).length]))}); } catch { return json(req,{error:'Request could not be completed'},500); }});
